language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # TOKEN
    - secure: HFpiakcLWrd/4VpUJBDSDe3KarLw9Hk7hEdD6Mant5hplOJUR8lLb5JramsEfO/ewI9MAnGcVLYBq1DXcp93PrwjWgrbWXi3UD5rHNgqUz2ml7Y5uAkNpUaBpWLjcH++GTxGDJYPZIMPD8+tVYlE7Xm/R+6RE+MEjyygrhx5i8gObAE1VfgSO8g3UnSnyLSkjuaZ5UkYGH33E7za4KN2hZq7peYj5zul2YgRHKi67CbyfmODsKsjX4tKMmQ2B0tCZz1xlofrniLdChmr//iGs493sGsTCXlhMEGYF7bIHPIqZ9iP0trOAO6QmassdU4X70GHcpmAtlIPy06j8h03JN7/IeW9gJPN+xOSp3v8cFzPGI6vPyRBwpjed7Wxw9RInlgy/lCUiLkHmCu6Jnj0bqT2ZiICxsVU58k4UD5zmmG/QwemR+maZ48aFY2I2BnpWAlDzvLsVxLZvtI+GBQvg0mQXT0XAH5/cZoYZ6cotQmAz8+bb+VtyW+qAGEVh5x4ecua14bUaO4N43jvyhCVAdYvtpg3nXYaE9t/oJsK/ocwuA7xpWUXSIqip/YI/EgAO+hVLYt6UUkPmYbuNIrMDoFo+cq+d2ZzUb7N15Hq0Le5szH7WNLc/zb/6u2V09pN7MoMgs6DPHvoJ8fG7XRswZ2II9BuKbNhxFkrTGJ8D4E=
    # SECRET
    - secure: oa6jyQgg/26EWs+zKXFZmGfCx4yna6mgvOZmrERmq9pnN/V+7/647UNUgqPqwBPjKlncE234URxfhqNwbP7giHCGnTDV6P5x03WS6IKBcsSfb1Sqf5I0/8x1XoxxXN5aj3+EzP64R9oQWJclImGNRugvdk4zjwi3zt7UeH35/6w5nx0bgsHTWAoJJBmKIruGAjeFg5DntzERQtAGs3jOPMu5nMoSYQCU/rj38RDmfL+YHxhWDz88yoXoxL2YhO5gicYho0OCdhkZm8RxdtW0TnYZJxB4D9m6hedQJ2syU43Hkh2J4R+yPXp/75w8sbmQzTi2w2e7mA/HHJbAfJKe1DESiCnopd5tdWpxddzA3XhT2ECxlQlYS9TK+ext8nTg4WZJs5l4VGcFnK3XuOtjXT85H+l3XCb7qQd/FeO7NN3a5sRSnc7vK+RSAkUZgpIXJ08vakKypwiHXUNpbGdbctR2umbdO4Dx7GoXYX79/Oi511eh0X2u10lR3Eg4WX9XLExuq5EyNXnvH94Ro1Kq44btAwuDED23fL8BdF9PzoIM+SbXseTQ7PdKjdYq/hdl+eTzs86vzs7PoajD+tXyw8SOVtetxZa34yA2jJrbWrWBPqX9fm9YhDXIpDQ3cp1ggu2xIPozCSSpt7IatPjgVV8V9rXV2CGDV7k2QSfHks8=
